medpoint:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: dev
      schema: dbt
      host: adb-1946775842002350.10.azuredatabricks.net
      http_path: /sql/1.0/warehouses/50102f70edc37bf0
      token: dapi8140304cdc4cd7577489a6e320aa7c1b-3
      threads: 1