
version: 2

models:
    - name: all_timestamps
      description: "All timestamps of interest"
      # columns:
      #     - name: WEBKEY
      #       description: "The primary key for this table"
      #       tests:
      #           - unique
      #           - not_null

