
version: 2

# models:
#     - name: AUTH_MASTERS_incremental
#       description: "Tracking changes to raw auth_masters"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null


