
version: 2

models:
    - name: auth_masters_incremental
      description: "Tracking changes to raw auth_masters"
      columns:
          - name: WEBKEY
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


